config/routes.rb
Proj::Application.routes.draw do
  resources :elements
  match 'elements/show_bitmap/:id' => 'elements#show_bitmap'

end

app/models/element.rb
class Element < ActiveRecord::Base
  attr_accessible :bitmap, :caption
  validates :bitmap, :presence => true
  validates :caption, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/elements_controller.rb
class ElementsController < ApplicationController

  # GET /elements
  # GET /elements.json
  def index
    @elements = Element.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @elements }
    end
  end

  # GET /elements/1
  # GET /elements/1.json
  def show
    @element = Element.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @element }
    end
  end

  # GET /elements/new
  # GET /elements/new.json
  def new
    @element = Element.new

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @element }
    end
  end

  # GET /elements/1/edit
  def edit
    @element = Element.find(params[:id])
  end

  # POST /elements
  # POST /elements.json
  def create
    @element = Element.new(params[:element])
    @element.bitmap = params[:bitmap].read
    # params[:bitmap].original_filename    # its file name on the client
    # params[:bitmap].content_type.chomp   # something like "image/jpg" or "image/png"

    respond_to do |format|
      if @element.save
        format.html { redirect_to @element, notice: 'Element was successfully created.' }
        format.json { render json: @element, status: :created, location: @element }
      else
        format.html { render action: "new" }
        format.json { render json: @element.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /elements/1
  # PUT /elements/1.json
  def update
    @element = Element.find(params[:id])
    @element.bitmap = params[:bitmap].read
    # params[:bitmap].original_filename    # its file name on the client
    # params[:bitmap].content_type.chomp   # something like "image/jpg" or "image/png"

    respond_to do |format|
      if @element.update_attributes(params[:element])
        format.html { redirect_to @element, notice: 'Element was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @element.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /elements/1
  # DELETE /elements/1.json
  def destroy
    @element = Element.find(params[:id])
    @element.destroy

    respond_to do |format|
      format.html { redirect_to elements_url }
      format.json { head :no_content }
    end
  end

  
  def show_bitmap
    @element = Element.find(params[:id])

    send_data(@element.bitmap, :type => 'image/png', :disposition => 'inline')
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/elements_helper.rb
module ElementsHelper
end

app/views/elements/_form.html.erb
<script>
$(function() {
   $('form').submit(function() {
      if(!$("form input[type=file]").val()) {
         alert('You must select a file!');
         return false;
      }
   });
});
</script>

<%= form_for(@element, :html => {:multipart => true, :accept => "image/*; capture=camera"}) do |f| %>
  <% if @element.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@element.errors.count, "error") %> prohibited this element from being saved:</h2>

      <ul>
      <% @element.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <% if @element.id %>
    <%= image_tag url_for(:controller => "elements", :action => "show_bitmap", :id => @element.id) %>
  <% end %>

  <div class="field">
      <%= f.label :bitmap %><br />
      <%= file_field_tag 'bitmap' %>
  </div> 
  <div class="field">
    <%= f.label :caption %><br />
    <%= f.text_field :caption %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/elements/edit.html.erb
<h1>Editing element</h1>

<%= render 'form' %>

<%= link_to 'Show', @element %> |
<%= link_to 'Back', elements_path %>

app/views/elements/index.html.erb
<h1>Listing elements</h1>

<table>
  <tr>
    <th>Bitmap</th>
    <th>Caption</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @elements.each do |element| %>
  <tr>
    <td><%= image_tag url_for(:controller => "elements", :action => "show_bitmap", :id => element.id) %></td>
    <td><%= element.caption %></td>
    <td><%= link_to 'Show', element %></td>
    <td><%= link_to 'Edit', edit_element_path(element) %></td>
    <td><%= link_to 'Destroy', element, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Element', new_element_path %>

app/views/elements/new.html.erb
<h1>New element</h1>

<%= render 'form' %>

<%= link_to 'Back', elements_path %>

app/views/elements/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <b>Bitmap:</b>
  <%= image_tag url_for(:controller => "elements", :action => "show_bitmap", :id => @element.id) %>
</p>

<p>
  <b>Caption:</b>
  <%= @element.caption %>
</p>


<%= link_to 'Edit', edit_element_path(@element) %> |
<%= link_to 'Back', elements_path %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Proj</title>
  <%= stylesheet_link_tag    "application", :media => "all" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>